VITE_AWS_REGION=${VITE_AWS_REGION}
VITE_USER_POOL_ID=${VITE_USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${VITE_USER_POOL_CLIENT_ID}
VITE_COGNITO_DOMAIN=${VITE_COGNITO_DOMAIN}
VITE_AMPLIFY_APP_URL=${VITE_AMPLIFY_APP_URL}
VITE_API_GATEWAY_URL=${VITE_API_GATEWAY_URL}